services:
    catalogdb:
        container_name: catalogdb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
            #- ./data:/data/db
        ports:
            - "27017:27017"

    basketdb:
        container_name: basketdb
        restart: always
        ports:
            - "6379:6379"

    orderdb:
        container_name: orderdb
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "SwN12345678"
            ACCEPT_EULA: "Y"


    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports: 
         - "5672:5672"
         - "15672:15672" 

